#!/usr/bin/env python

import sys

from rqt_navigation.rqt_navigation import RQTNavigation
from rqt_gui.main import Main

plugin = 'rqt_navigation'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
