# int32 id

# uint8 S_NAME=0
# uint8 SIGN=1	
# uint8 LIGHT=2
# uint8 LOCALIZE=3
# uint8 tag_type

# string street_name

# uint8 STOP=4
# uint8 YIELD=5
# uint8 NO_RIGHT=6
# uint8 NO_LEFT=7
# uint8 ONEWAY_RIGHT=8
# uint8 ONEWAY_LEFT=9
# uint8 FOUR_WAY=10
# uint8 RIGHT_T_INTERSECT=11
# uint8 LEFT_T_INTERSECT=12
# uint8 T_INTERSECTION=13
# uint8 DO_NOT_ENTER=14
# uint8 PEDESTRIAN=15
# uint8 traffic_sign_type

# string vehicle_name

