#!/usr/bin/env python
import sys


if __name__ == '__main__':
    try:
        from duckietown_utils.sanity_checks import do_all_checks
        from duckietown_utils import col_logging  # @UnusedImport
    except ImportError as e:
        print('Could not import duckietown_utils: %s' % e)
        sys.exit(1)
    
    failures = do_all_checks()

    if not failures:
        print('Everything went well.')
        sys.exit(0)
    else:
        print('I obtained failures: %s. Returning non-zero.' % failures)
        sys.exit(1)


if __name__ == '__main__':
    all_checks()
