img_size: [120,160]
top_cutoff: 40

detector: 
  - line_detector.LineDetectorHSV
  - configuration:
      dilation_kernel_size: 3
      canny_thresholds: [60,150]
      hough_threshold: 20
      hough_min_line_length: 3
      hough_max_line_gap:    1

      # wite is "blue", red is "red, yellow is stop
      hsv_white1:  [90,80,50] #blue
      hsv_white2:  [110,255,255] #blue
      hsv_yellow1: [25,50,50]
      hsv_yellow2: [45,255,255]
      hsv_red1:    [0,100,100]
      hsv_red2:    [15,255,255]
      hsv_red3:    [165,100,100]
      hsv_red4:    [180,255,255]
